steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/citric-kit-489316-g6/sarvesh/flask-demo:latest'
    - '.'
 
# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/citric-kit-489316-g6/sarvesh/flask-demo:latest'
 
# Step 3: Update GKE deployment with the new image
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/flask-deployment
    - flask-container=asia-south1-docker.pkg.dev/citric-kit-489316-g6/sarvesh/flask-demo:latest
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-west1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sarveshcluster-1'
 
# Step 4: Verify rollout
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - rollout
    - status
    - deployment/flask-deployment
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-west1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sarveshcluster-1'
 
images:
  - 'asia-south1-docker.pkg.dev/citric-kit-489316-g6/sarvesh/flask-demo:latest'
